language: python
python:
  - "3.6"
#install:
#  - pip install -r requirements.txt

#script:
#  - pytest

services:
  - docker

before_script: pip install docker-compose

script:
  - docker-compose run app sh -c "python manage.py test"
  #- docker-compose run app sh -c "python manage.py test && flake8"
